const KEY='arsGolfAnalytics.v1';
const COURSE={name:'Shenandoah Country Club',construction:[2,3,8],pars:[4,4,3,4,5,4,4,3,5,4,4,4,5,3,4,5,4,4]};
const legacy=(date,tee,total,front,back,holes=null)=>({id:'seed-'+date,date,player:'Ars',course:COURSE.name,tee,total,front,back,holes:holes?.map((score,i)=>({number:i+1,par:COURSE.pars[i],score,putts:null,fairway:'N/A',gir:null,penalties:0,sand:false,upDown:null,notes:'',construction:COURSE.construction.includes(i+1)}))||null,seeded:true});
const SEED=[legacy('2026-06-23','Blue',96,47,49),legacy('2026-06-30','Black',101,53,48),legacy('2026-07-07','Blue',86,44,42),legacy('2026-07-14','Blue',95,49,46),legacy('2026-07-19','Blue',89,44,45,[6,7,3,4,6,5,4,4,5,6,5,5,7,3,5,5,4,5]),legacy('2026-07-21','Blue',99,47,52,[4,6,3,5,9,7,5,5,3,7,4,5,7,6,6,6,5,6]),legacy('2026-07-25','Blue',102,54,48),legacy('2026-08-01','Blue',104,54,50,[6,8,4,8,7,6,5,6,4,5,5,5,6,5,7,7,4,6])];
let state=load(),draft=state?.draft||null,deferredPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch(e){}return null}state=state&&Array.isArray(state.rounds)?state:{rounds:SEED,profile:{player:'Ars',course:COURSE.name,tee:'Blue'}};
function save(){state.draft=draft;localStorage.setItem(KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function nav(view){$$('.view,nav button').forEach(e=>e.classList.remove('active'));$('#'+view).classList.add('active');$(`nav button[data-view="${view}"]`).classList.add('active');render(view);scrollTo(0,0)}
function avg(a){return a.length?(a.reduce((x,y)=>x+y,0)/a.length):0}function pct(a,b){return b?Math.round(a/b*100)+'%':'—'}
function render(view){({dashboard,play,rounds,analytics,settings}[view]||dashboard)()}
function dashboard(){const rs=[...state.rounds].sort((a,b)=>a.date.localeCompare(b.date)),scores=rs.map(r=>r.total),best=Math.min(...scores),last=rs.at(-1);$('#dashboard').innerHTML=`<div class="hero"><span class="eyebrow">2026 SEASON</span><div class="row spread"><div><p>Scoring average</p><div class="big">${avg(scores).toFixed(1)}</div></div><div class="pill">${rs.length} rounds</div></div><p>Best ${best} · Latest ${last.total} on ${fmtDate(last.date)}</p></div><div class="grid four"><div class="card metric"><b>${best}</b><span>Season best</span></div><div class="card metric"><b>${avg(rs.map(r=>r.front)).toFixed(1)}</b><span>Front nine</span></div><div class="card metric"><b>${avg(rs.map(r=>r.back)).toFixed(1)}</b><span>Back nine</span></div><div class="card metric"><b>${trend(scores)}</b><span>Recent trend</span></div></div><button class="primary wide" onclick="startRound()">${draft?'Continue round':'Start a round'}</button><h2 class="section-title">Scoring trend</h2><div class="card">${chart(rs)}</div><h2 class="section-title">Recent rounds</h2>${rs.slice(-3).reverse().map(roundCard).join('')}`}
function trend(s){if(s.length<4)return'—';const d=avg(s.slice(-3))-avg(s.slice(0,3));return(d>0?'+':'')+d.toFixed(1)}
function chart(rs){const min=Math.min(...rs.map(r=>r.total))-4,max=Math.max(...rs.map(r=>r.total))+2;return `<div class="chart">${rs.map(r=>`<div class="bar-wrap"><b>${r.total}</b><div class="bar" style="height:${20+(max-r.total)/(max-min)*100}px"></div><small>${r.date.slice(5).replace('-','/')}</small></div>`).join('')}</div>`}
function roundCard(r){return `<button class="card round wide" onclick="editRound('${r.id}')"><span class="score-badge">${r.total}</span><span><h3>${fmtDate(r.date)} · ${esc(r.tee)} tees</h3><p>${r.course} · ${r.front} / ${r.back}</p></span><span>›</span></button>`}
function startRound(){if(!draft){draft={id:'r-'+Date.now(),date:new Date().toISOString().slice(0,10),player:state.profile.player,course:state.profile.course,tee:state.profile.tee,index:0,holes:Array.from({length:18},(_,i)=>({number:i+1,par:COURSE.pars[i],score:COURSE.pars[i],putts:2,fairway:[2,7,13].includes(i)?'N/A':'Hit',gir:false,penalties:0,sand:false,upDown:false,notes:'',construction:COURSE.construction.includes(i+1)}))};save()}nav('play')}
function play(){if(!draft){$('#play').innerHTML=`<div class="hero"><span class="eyebrow">NEW ROUND</span><h2>Ready when you are.</h2><p>Track each shot outcome hole by hole. Everything stays on this device.</p></div><div class="card" style="margin-top:16px"><label>Date</label><input id="newDate" type="date" value="${new Date().toISOString().slice(0,10)}"><label>Player</label><input id="newPlayer" value="${esc(state.profile.player)}"><label>Course</label><input id="newCourse" value="${esc(state.profile.course)}"><label>Tees</label><select id="newTee"><option>Blue</option><option>Black</option><option>White</option><option>Gold</option></select><button class="primary wide" style="margin-top:18px" onclick="beginConfigured()">Begin round</button></div>`;return}holeForm()}
function beginConfigured(){const config={date:$('#newDate').value,player:$('#newPlayer').value,course:$('#newCourse').value,tee:$('#newTee').value};draft={id:'r-'+Date.now(),...config,index:0,holes:Array.from({length:18},(_,i)=>({number:i+1,par:COURSE.pars[i],score:COURSE.pars[i],putts:2,fairway:[2,7,12].includes(i)?'N/A':'Hit',gir:false,penalties:0,sand:false,upDown:false,notes:'',construction:COURSE.construction.includes(i+1)}))};save();play()}
function holeForm(){const i=draft.index,h=draft.holes[i],toPar=draft.holes.slice(0,i).reduce((n,x)=>n+x.score-x.par,0);$('#play').innerHTML=`<div class="hole-head"><div><span class="eyebrow" style="color:var(--green2)">HOLE ${i+1} OF 18</span><h2>Hole ${h.number}</h2></div><div class="pill">Par ${h.par} · ${toPar===0?'E':toPar>0?'+'+toPar:toPar}</div></div><div class="progress"><i style="width:${(i+1)/18*100}%"></i></div>${h.construction?'<div class="notice">Construction-shortened hole — retained for historical interpretation.</div>':''}<div class="card"><label>Score</label>${counter('score',h.score,1)}<label>Putts</label>${counter('putts',h.putts,0)}<label>Fairway result</label>${segments('fairway',['Hit','Left','Right','Short','Long','N/A'],h.fairway)}<label>Green in regulation</label>${segments('gir',['Yes','No'],h.gir?'Yes':'No')}<div class="grid"><div><label>Penalty strokes</label><input id="penalties" type="number" min="0" value="${h.penalties}" onchange="setHole('penalties',+this.value)"></div><div><label>Sand opportunity</label><select onchange="setHole('sand',this.value==='Yes')"><option${!h.sand?' selected':''}>No</option><option${h.sand?' selected':''}>Yes</option></select></div></div><label>Up-and-down</label>${segments('upDown',['Yes','No','N/A'],h.upDown===null?'N/A':h.upDown?'Yes':'No')}<label>Notes</label><textarea oninput="setHole('notes',this.value)" placeholder="Optional shot notes">${esc(h.notes)}</textarea></div><div class="actions">${i?'<button class="secondary" onclick="moveHole(-1)">Back</button>':''}<button class="primary" onclick="${i===17?'finishRound()':'moveHole(1)'}">${i===17?'Review round':'Next hole'}</button></div>`}
function counter(k,v,min){return `<div class="counter"><button class="secondary" onclick="bump('${k}',-1,${min})">−</button><b>${v}</b><button class="secondary" onclick="bump('${k}',1,${min})">＋</button></div>`}
function segments(k,vals,v){return `<div class="seg" style="grid-template-columns:repeat(${Math.min(vals.length,4)},1fr)">${vals.map(x=>`<button class="${x===v?'selected':''}" onclick="setChoice('${k}','${x}')">${x}</button>`).join('')}</div>`}
function bump(k,n,min){draft.holes[draft.index][k]=Math.max(min,draft.holes[draft.index][k]+n);save();holeForm()}function setHole(k,v){draft.holes[draft.index][k]=v;save()}function setChoice(k,v){setHole(k,k==='gir'?v==='Yes':k==='upDown'?v==='N/A'?null:v==='Yes':v);holeForm()}function moveHole(n){draft.index+=n;save();holeForm()}
function finishRound(){const total=draft.holes.reduce((n,h)=>n+h.score,0),front=draft.holes.slice(0,9).reduce((n,h)=>n+h.score,0),back=total-front;$('#modalBody').innerHTML=`<span class="eyebrow" style="color:var(--green2)">ROUND COMPLETE</span><h2>${total} total</h2><div class="grid"><div class="card metric"><b>${front}</b><span>Front</span></div><div class="card metric"><b>${back}</b><span>Back</span></div></div><p class="muted">Save this round to history? You can edit it later.</p><div class="actions"><button class="secondary">Keep editing</button><button type="button" class="primary" onclick="commitRound()">Save round</button></div>`;$('#modal').showModal()}
function commitRound(){const r={...draft,index:undefined,total:draft.holes.reduce((n,h)=>n+h.score,0),front:draft.holes.slice(0,9).reduce((n,h)=>n+h.score,0)};r.back=r.total-r.front;delete r.index;state.rounds.push(r);draft=null;save();$('#modal').close();toast('Round saved');nav('rounds')}
function rounds(){const rs=[...state.rounds].sort((a,b)=>b.date.localeCompare(a.date));$('#rounds').innerHTML=`<div class="row spread"><div><span class="eyebrow" style="color:var(--green2)">SCORECARD</span><h2>Round history</h2></div><span class="pill">${rs.length} rounds</span></div>${rs.map(roundCard).join('')}`}
function editRound(id){const r=state.rounds.find(x=>x.id===id);$('#modalBody').innerHTML=`<h2>Edit round</h2><label>Date</label><input id="eDate" type="date" value="${r.date}"><label>Tees</label><input id="eTee" value="${esc(r.tee)}"><div class="grid"><div><label>Front</label><input id="eFront" type="number" value="${r.front}"></div><div><label>Back</label><input id="eBack" type="number" value="${r.back}"></div></div>${r.holes?`<div class="notice">Hole scores are available. Editing nine-hole totals here will proportionally change only the summary; use totals carefully.</div>`:'<p class="muted">This legacy round has summary data only.</p>'}<div class="actions"><button type="button" class="danger" onclick="deleteRound('${id}')">Delete</button><button type="button" class="primary" onclick="saveEdit('${id}')">Save</button></div>`;$('#modal').showModal()}
function saveEdit(id){const r=state.rounds.find(x=>x.id===id);r.date=$('#eDate').value;r.tee=$('#eTee').value;r.front=+$('#eFront').value;r.back=+$('#eBack').value;r.total=r.front+r.back;save();$('#modal').close();toast('Round updated');rounds()}function deleteRound(id){if(!confirm('Delete this round? This cannot be undone.'))return;state.rounds=state.rounds.filter(r=>r.id!==id);save();$('#modal').close();rounds()}
function analytics(){const rs=state.rounds, detailed=rs.filter(r=>r.holes),holes=detailed.flatMap(r=>r.holes),eligible=holes.filter(h=>h.fairway!=='N/A'),girKnown=holes.filter(h=>h.gir!==null),par=COURSE.pars.reduce((a,b)=>a+b,0),byHole=COURSE.pars.map((p,i)=>{const vals=detailed.map(r=>r.holes[i]?.score).filter(Number.isFinite);return {n:i+1,p,avg:avg(vals),d:avg(vals)-p,c:COURSE.construction.includes(i+1)}});$('#analytics').innerHTML=`<span class="eyebrow" style="color:var(--green2)">PERFORMANCE</span><h2>Season analytics</h2><div class="grid four"><div class="card metric"><b>${avg(rs.map(r=>r.total)).toFixed(1)}</b><span>Score avg</span></div><div class="card metric"><b>${pct(eligible.filter(h=>h.fairway==='Hit').length,eligible.length)}</b><span>Fairways</span></div><div class="card metric"><b>${pct(girKnown.filter(h=>h.gir).length,girKnown.length)}</b><span>GIR</span></div><div class="card metric"><b>${avg(rs.map(r=>r.total-par)).toFixed(1)}</b><span>Avg to par</span></div></div><h3 class="section-title">Miss pattern</h3><div class="card">${['Hit','Left','Right','Short','Long'].map(x=>`<div class="switch"><span>${x}</span><b>${pct(eligible.filter(h=>h.fairway===x).length,eligible.length)}</b></div>`).join('')}</div><h3 class="section-title">Hole-by-hole</h3><div class="card"><table><thead><tr><th>Hole</th><th>Par</th><th>Avg</th><th>To par</th></tr></thead><tbody>${byHole.map(h=>`<tr><td>${h.n}${h.c?'*':''}</td><td>${h.p}</td><td>${h.avg?h.avg.toFixed(1):'—'}</td><td>${h.avg?(h.d>=0?'+':'')+h.d.toFixed(1):'—'}</td></tr>`).join('')}</tbody></table><p class="muted">* Construction-shortened. Hole analytics use ${detailed.length} rounds with hole-level data.</p></div>`}
function settings(){$('#settings').innerHTML=`<span class="eyebrow" style="color:var(--green2)">YOUR DATA</span><h2>Backup & preferences</h2><div class="card"><label>Default player</label><input id="sPlayer" value="${esc(state.profile.player)}"><label>Default course</label><input id="sCourse" value="${esc(state.profile.course)}"><label>Default tees</label><input id="sTee" value="${esc(state.profile.tee)}"><button class="primary wide" style="margin-top:16px" onclick="saveProfile()">Save defaults</button></div><h3 class="section-title">Data portability</h3><div class="card"><button class="secondary wide" onclick="exportJSON()">Export JSON backup</button><button class="secondary wide" style="margin-top:9px" onclick="$('#importFile').click()">Import JSON backup</button><button class="secondary wide" style="margin-top:9px" onclick="exportCSV()">Export rounds as CSV</button><p class="muted">Data is stored only in this browser. Export a backup before clearing browser data or changing phones.</p></div>`}
function saveProfile(){state.profile={player:$('#sPlayer').value,course:$('#sCourse').value,tee:$('#sTee').value};save();toast('Defaults saved')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download(`ars-golf-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json')}
function exportCSV(){const head=['date','player','course','tees','total','front','back','fairways_hit','fairways_eligible','gir','gir_known','putts','penalties'];const rows=state.rounds.map(r=>{const h=r.holes||[],fw=h.filter(x=>x.fairway!=='N/A'),g=h.filter(x=>x.gir!==null);return [r.date,r.player,r.course,r.tee,r.total,r.front,r.back,fw.filter(x=>x.fairway==='Hit').length,fw.length,g.filter(x=>x.gir).length,g.length,h.reduce((n,x)=>n+(x.putts||0),0),h.reduce((n,x)=>n+(x.penalties||0),0)]});download('ars-golf-rounds.csv',[head,...rows].map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
$('#importFile').addEventListener('change',async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.rounds))throw Error();if(confirm(`Replace local data with ${data.rounds.length} imported rounds?`)){state=data;draft=data.draft||null;save();toast('Backup imported');nav('dashboard')}}catch(err){alert('That file is not a valid Ars Golf backup.')}e.target.value=''})
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
$$('nav button').forEach(b=>b.onclick=()=>nav(b.dataset.view));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{deferredPrompt?.prompt();await deferredPrompt?.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));dashboard();
